language: ruby
before_install:
  - cp yamls/database.yml.travisCI config/database.yml
  - mysql -e 'create database le_test;'
  - mysql -e 'SET GLOBAL innodb_flush_log_at_trx_commit=2'
bundler_args: --without development production
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - phantomjs --version
script:
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec cucumber --profile travis
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - patch
    - sprint