language: ruby
before_install:
  - rm Gemfile.lock
bundler_args: --without development production
before_script:
  - bundle install --without development production
  - bundle check
  - cp yamls/database.yml.travisCI config/database.yml
  - mysql -e 'create database le_test;'
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - phantomjs --version
script:
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec cucumber --profile travis
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
branches:
  only:
    - master
    - devel